apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlb-ingress
  namespace: nlb-tool
spec:
  ingressClassName: nginx 
  rules:
  - host: "nlb.tonytechlab.com" # Khớp với APP_HOST_URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-loadbalangcer-tool-svc # Trỏ vào ClusterIP service
            port:

              number: 80
