apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdGVyLnRvbnl0ZWNobGFiLmNvbSI6eyJ1c2VybmFtZSI6InJvb3QiLCJwYXNzd29yZCI6ImdscGF0LVN1bEdLMlpqQ0RtdFN2RER3aWNyRlc4Nk1RcDFPakVILjAxLjB3MTA1NGg2cSIsImF1dGgiOiJjbTl2ZERwbmJIQmhkQzFUZFd4SFN6SmFha05FYlhSVGRrUkVkMmxqY2taWE9EWk5VWEF4VDJwRlNDNHdNUzR3ZHpFd05UUm9ObkU9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-registry-creds
  namespace: nlb-tool
type: kubernetes.io/dockerconfigjson
